option(
  'build_tests',
  type: 'boolean',
  value: true,
  description: 'Build and register the test suite',
)

option(
  'build_samples',
  type: 'boolean',
  value: false,
  description: 'Build the sample programs',
)

option(
  'docdir',
  type: 'string',
  value: 'share/doc/pcg-c',
  description: 'Installation directory for documentation (relative to prefix)',
)
