_lib_sources = files(
    'pcg-advance-128.c',
    'pcg-advance-16.c',
    'pcg-advance-32.c',
    'pcg-advance-64.c',
    'pcg-advance-8.c',
    'pcg-global-32.c',
    'pcg-global-64.c',
    'pcg-output-128.c',
    'pcg-output-16.c',
    'pcg-output-32.c',
    'pcg-output-64.c',
    'pcg-output-8.c',
    'pcg-rngs-128.c',
    'pcg-rngs-16.c',
    'pcg-rngs-32.c',
    'pcg-rngs-64.c',
    'pcg-rngs-8.c',
)
