name: BSD
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths: &shared_paths
      - '**'
      - '!**.yml'
      - '!**.md'
      - '**/bsd.yml'

  pull_request:
    branches: [ master ]
    paths: *shared_paths

jobs:
  BSD:
    name: BSD (${{ matrix.os }} ${{ matrix.version }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: freebsd
            version: '15.0'
            install: sudo pkg install -y meson ninja
          - os: openbsd
            version: '7.9'
            install: |
              echo https://cdn.openbsd.org/pub/OpenBSD | sudo tee /etc/installurl
              sudo pkg_add meson ninja
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup ${{ matrix.os }} ${{ matrix.version }}
      uses: cross-platform-actions/action@v1
      with:
        operating_system: ${{ matrix.os }}
        version: ${{ matrix.version }}

    - name: Install dependencies
      shell: cpa.sh {0}
      run: ${{ matrix.install }}

    - name: Setup
      shell: cpa.sh {0}
      run: CFLAGS="-Werror" meson setup _build

    - name: Compile
      shell: cpa.sh {0}
      run: meson compile -C _build

    - name: Test and install
      shell: cpa.sh {0}
      run: |
        meson test --no-stdsplit -v -C _build
        meson install --destdir=install_test -C _build
