name: MSVC
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths: &shared_paths
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/msvc.yml'

  pull_request:
    branches: [ master ]
    paths: *shared_paths

jobs:
  msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install meson and ninja
      run: pip install meson ninja

    - name: Meson setup
      run: meson setup _build

    - name: Build
      run: meson compile -C _build

    - name: Test
      run: meson test --no-stdsplit -v -C _build
